### ISSUE TITLE
Environmental variables - discussion

### ISSUE THREAD

**Issue by lbesnard** [aodn/data-services#107]
# Environmental variables - discussion

A few weeks ago, @danfruehauf has set up environmental variables on 10-nsp so POs can use them for their scripts. The main reason for this is to make this repo scalable. In the last few years, we've changed infrastructure quite a few times. It is pretty clear that being scalable is a necessity.

However, I feel like we haven't taken into account the different user cases, and these environment variables seems to me to be a burden as well as being quite hard to use. 

I'd like to have everyone's opinion on this matter, and to know better how POs are thinking of using them. 

## Current  environmental variables

|Name              |Default                    |Purpose                        |
|------------------|---------------------------|-------------------------------|
|$OPENDAP_DIR      |/mnt/opendap               |OpenDAP                        |
|$PUBLIC_DIR       |/mnt/imos-t4/IMOS/public   |Public                         |
|$ARCHIVE_DIR      |/mnt/imos-t4/IMOS/archive  |Archive                        |
|$INCOMING_DIR     |/mnt/imos-t4/IMOS/staging  |Incoming                       |
|$OPENDAP_IMOS_DIR |$OPENDAP_DIR/1/IMOS/opendap|IMOS OpenDAP                   |
|$PUBLIC_IMOS_DIR  |$PUBLIC_DIR                |IMOS public                    |
|$ARCHIVE_IMOS_DIR |$ARCHIVE_DIR               |IMOS archive                   |
|$WIP_DIR          |/mnt/ebs/wip               |Work In Progress tmp dir       |
|$DATA_SERVICES_DIR|/mnt/ebs/data-services     |Where this git repo is deployed|
|$LOG_DIR          |/mnt/ebs/log/data-services |Designated log dir             |

## 
Most of our scripts currently use a file, generally called **config.txt** . Prior to the 'environmental variables' era, a config file was written such as :

**config.txt**
```bash
script.path             = /mnt/ebs/data-services/AATAMS/AATAMS_sattag_nrt
dataWIP.path            = /mnt/imos-t4/project_officers/wip/AATAMS/AATAMS_sattag_nrt
australianTags.filepath = /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AATAMS/metadata/aatams_sattag_metadata.csv
dataInput.path          = /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AATAMS/aatams_sattag_nrt/unzipped
```

This config file can then be used easily by any programming language.

### in Matlab :
```matlab
dataWIP_path = readConfig('dataWIP.path', 'config.txt','=');
```

### in Python :
```python
from configobj import ConfigObj 
config       = ConfigObj('config.txt')
dataWIP_path = config.get('dataWIP.path')
```

### in Bash;
```bash
configfile=config.txt
ii=0
while read line; do
if [[ "$line" =~ ^[^#]*= ]]; then
        #http://stackoverflow.com/questions/369758/how-to-trim-whitespace-from-bash-variable
        name[ii]=`echo $line | cut -d'=' -f 1 | sed -e 's/^ *//' -e 's/ *$//'`
        value[ii]=`echo $line | cut -d'=' -f 2- | sed -e 's/^ *//' -e 's/ *$//'`
        ((ii++))
fi
done <$configfile

# this part of the code finds the script.path value in the config.txt
for (( jj = 0 ; jj < ${#value[@]} ; jj++ ));
do
    if [[ "${name[jj]}" =~ "dataWIP.path" ]] ; then
         dataWIP_path=${value[jj]} ;
    fi
done
```

It often happens that one main script calls actually many programming language routines. This happens because we sometimes find on internet routines written in Perl, Python or other which do the job we want, and don't or can't reinvent the wheel all the time. 

For example the previous version of the AATAMS_DM script used to 
1 - run a shell script, which
2 - who called Matlab, which
3 - would call Python to convert some Microsoft Access Database files.

This is to point out that some codes can be 'complex' in terms of technology being used.

##  How is the config file supposed to be written ?

Nothing has been cleared since the beginning. The env var were created, ready to be used. But how ? No one sat down to talk about it.

### Possibility 1
It was first suggested to hardcode a Matlab function into the config file to read the environmental variable. In Matlab, this function is called **getenv**. For example, if one wants to use the $OPENDAP_IMOS_DIR variable, the config file would be written such as :

**config.txt**
```bash
opendapFAIMMS.path  = strcat(getenv('OPENDAP_IMOS_DIR'),'/FAIMMS')
```

1) Let's try to read this in matlab

```matlab
testVar = readConfig('opendapFAIMMS.path', 'config.txt','=');
class testVar
>> class testVar

ans =

char

>> testVar

testVar =

strcat(getenv('OPENDAP_IMOS_DIR'),'/FAIMMS')
```

This means that loaded in Matlab, it will be loaded as a string, and not as a command to run. The only way to change this would be to change all our Matlab scripts to convert the string into a command. Every single *.m file which would use this variable would have to be changed. Again more work and a source of mistake.

In Matlab, the command **eval** executes a Matlab expression in text string. So all our *.m files would need to use 

```matlab
testVar = readConfig('opendapFAIMMS.path', 'config.txt','=');
testVar = eval(testVar)
```

Anyway, writing a config file this way shows that it could potentially only be read by Matlab, and nor Python, nor bash nor ... which is clearly not possible for many scripts.

### Possibility 2

We saw above that hardcoding a config file either : 

**config.txt** for Matlab
```bash
opendapFAIMMS.path  = strcat(getenv('OPENDAP_IMOS_DIR'),'/FAIMMS')
```

or

**config.txt** for Bash
```bash
opendapFAIMMS.path  = $OPENDAP_IMOS_DIR/FAIMMS
```

is not the way to go if more than one programming language is going to use config.txt.

In this case, it seems like the only possible way is not to add the environmental variable part into the config file, but into the programming language itself. In other words, hardcoding half of the configuration into the different matlab, bash and python script. It seems a bit counter productive. See example below :

**config.txt**
```bash
opendapFAIMMS.path  = FAIMMS
```

and on Matlab
```matlab
opendapFaimmsPath = strcat(getenv(OPENDAP_IMOS_DIR) , readConfig('opendapFAIMMS.path', 'config.txt','=');
```

Not to mention that those Matlab, Python etc scripts will need to check that they do exist, and create default env variables if not. Which means more coding/testing ... for something which is already works.

#### Possibility 2 - Cons 1 
Although it seems like not much, modifying every single routine to handle this can take a lot of time, and is never done without mistakes. 

#### Possibility 2 - Cons 2 
Because a part of the configuration would be hard coded into the scripts, if for any reason (and they exists), a file used by a script has to be relocated from $PUBLIC_IMOS_DIR to $ARCHIVE_IMOS_DIR

or even in a near future, once the copy of data will changed from $OPENDAP_IMOS_DIR to $INCOMING_DIR once PO's won't have any writing access, then **ALL** *.m *.sh *.py will again have to be changed. It doesn't seem serious at all, no compiled program works like this, they read a config file, that is all.

#### Possibility 2 - Cons 3
This also make things way more difficult to code and test on our machines. This is being forced to develop in a rigid environment.

#### Possibility 2 - Cons 4 
To give some of our codes to third parties becomes impossible.

### Possibility 3
Unknown - anyone welcome to edit

## Which solution ?

I'm seeking for help and advice here. But IMO we're not going towards the right path, although we need to find a way to make this repository scalable.

### Solution 1

A **config.txt.bckp** could be created with all env variables written in :

**config.txt.bckp**
```bash
opendapFAIMMS.path  = $OPENDAP_IMOS_DIR/FAIMMS
```

This config.txt.bckp could be read and translated by a common bash script ninjaTranslate.sh for the data-services repo. This bash script should :
1) find all **config.txt.bckp** in the data-services repo
2) translate all env variables found in **config.txt.bckp** to their correct value
3) create equivalent **config.txt** files with the correct values

This would be equivalent as applying a patch to the full repo every time the master branch gets checked out. 

### Solution 2 

If we want to stick with  **Possibility 1**  mentioned above, as many config files as programming language being used for one software will need to be created.

-config.py.txt
-config.bash.txt
-config.mat.txt

This seems really dirty, and again a source of mistakes

### Solution 3 
running out of ideas

## Conclusion

I'm sure the Dev's team would have heaps of ideas and feedbacks. @dnahodil , since you're the Man this week, could we sat down with a few people sometimes  ?

**Comment by mhidas** [comment]
@lbesnard Can we close this issue? I think we've got environment vars pretty sorted.
