### ISSUE TITLE
ANMN T-gridded product file names don't meet naming convention

### ISSUE THREAD

**Issue by mhidas** [aodn/data-services#324]
The process creates file names like this:
IMOS_ANMN-NSW_Temperature_20100702T003500Z_CH070_FV02_CH070-1007-regridded_END-20100907T000500Z_C-20141211T025746Z.nc

This doesn't actually meet the [IMOS file naming convention](http://help.aodn.org.au/help/sites/help.aodn.org.au/files/IMOS%20NetCDF%20File%20Naming%20Convention_0.pdf) because the third field (after the sub-facility code) should consist of data codes indicating the type of parameters in the file. In this case it should be 'TZ' instead of 'Temperature'.

**Comment by bpasquer** [comment]
Closing .This dataset has been decommissioned.
