### ISSUE TITLE
messy repo

### ISSUE THREAD

**Issue by lbesnard** [aodn/data-services#33]
I don't want to police people, but the repo starts to be pretty messy. When we first had a chat about it, we mentionned this (see readme)
```
Folder stucture
The suggested naming convention we agreed on with the developpers, regarding the different PO's scripts was : [FACILITY_NAME]/[SUB-FACILITY_NAME][script_name][programing_language]

example : FAIMMS/faimms_data_rss_channels_process_matlab
```

Most of the folders don't respect this, don't have an easy to read folder hierarchy, no readme file to know what those scripts are supposed to do... 

I think we (PO's) should all try to make this repo more consistent and cleaner. 

Thoughts anyone ?

**Comment by danfruehauf** [comment]
So, should we close this?

I think we're all on the right path of getting this repo to be nicely organized (hierarchies, reviews, tests, etc).

**Comment by bpasquer** [comment]
i think we can close it

**Comment by jkburges** [comment]
:+1:
