### ISSUE TITLE
Could not find uploader for file

### ISSUE THREAD

**Issue by mhidas** [aodn/data-services#390]
A recent upload from one of the regular ANMN uploaders had a couple of erroneous files, but the error message was sent to me because:

```
Mar 21 11:28:56 10-aws-syd ANMN_NRS: Could not find uploader for file '/mnt/ebs/tmp/tmp.Y3UBpkI1oe/IMOS_ANMN-NRS_CDEKSTUZ_20090527T020337Z_NSNSI_FV00_Profile-SBE-19plus_C-20151214T043847Z.nc'
```

**Comment by danfruehauf** [comment]
I think I actually know what the problem is. That is related to:
https://github.com/aodn/chef/commit/536cede8287dfff5748ee84bb8d8137b76416bc3

So `$INCOMING_FILE` does not refer to the uploaded file (with its full path) but to the file after it is moved into the sandboxed directory.

Possible solution: Have another variable to store `$ORIGINAL_UPLOADED_FILE` or something in this form, then change the email probing to utilize that variable.

**Comment by danfruehauf** [comment]
I'm not going to take responsibility for that fix since I won't be here, but here it is:
 * aodn/chef#279
 * #391

**Comment by mhidas** [comment]
The two PR's above have been merged & deployed. As far as I can tell, this is fixed.

**Comment by mhidas** [comment]
This has been recurring again sporadically over the past few weeks. It's a pain because it means the uploader doesn't get notified when a file has problems and can't be published.

e.g.
```
mhidas@10-aws-syd:/mnt/ebs/log/data-services$ grep uploader process.log
Nov  9 13:50:50 10-aws-syd ANMN_NRS: Could not find uploader for file '/mnt/ebs/incoming/ANMN/NRS/IMOS_ANMN-NRS_AETVZ_20160606T000000Z_NRSNSI-ADCP_FV00_NRSNSI-ADCP-14-2016-06-Sentinel-or-Monitor-Workhorse-ADCP-63_END-20161027T022959Z_C-20161108T224245Z.nc'
Nov  9 13:50:53 10-aws-syd ANMN_NRS: Could not find uploader for file '/mnt/ebs/incoming/ANMN/NRS/IMOS_ANMN-NRS_AETVZ_20160606T000000Z_NRSNSI-ADCP_FV01_NRSNSI-ADCP-14-2016-06-Sentinel-or-Monitor-Workhorse-ADCP-63_END-20161027T022959Z_C-20161108T224245Z.nc'
Nov  9 13:50:55 10-aws-syd ANMN_NRS: Could not find uploader for file '/mnt/ebs/incoming/ANMN/NRS/IMOS_ANMN-NRS_CKOSTUZ_20160605T001342Z_NRSNSI-SubSurface_FV00_NRSNSI-SubSurface-17-2016-06-WQM-20_END-20161026T035924Z_C-20161108T224050Z.nc'
Nov  9 13:50:58 10-aws-syd ANMN_NRS: Could not find uploader for file '/mnt/ebs/incoming/ANMN/NRS/IMOS_ANMN-NRS_CKOSTUZ_20160605T001342Z_NRSNSI-SubSurface_FV01_NRSNSI-SubSurface-17-2016-06-WQM-20_END-20161026T035924Z_C-20161108T224050Z.nc'
Nov  9 13:51:00 10-aws-syd ANMN_NRS: Could not find uploader for file '/mnt/ebs/incoming/ANMN/NRS/IMOS_ANMN-NRS_CKOSTUZ_20160605T001354Z_NRSNSI-SubSurface_FV00_NRSNSI-SubSurface-17-2016-06-WQM-60_END-20161026T025924Z_C-20161108T224051Z.nc'
Nov  9 13:51:04 10-aws-syd ANMN_NRS: Could not find uploader for file '/mnt/ebs/incoming/ANMN/NRS/IMOS_ANMN-NRS_CKOSTUZ_20160605T001354Z_NRSNSI-SubSurface_FV01_NRSNSI-SubSurface-17-2016-06-WQM-60_END-20161026T025924Z_C-20161108T224051Z.nc'

mhidas@10-aws-syd:/mnt/ebs/log/data-services$ zgrep 'uploader' process.log.?.gz
process.log.5.gz:Nov  4 10:03:58 10-aws-syd ANFOG_DM: Could not find uploader for file '/mnt/ebs/tmp/tmp.AGx2Lqyxbm/Yamba20160415.zip'
process.log.6.gz:Nov  4 09:56:03 10-aws-syd ANFOG_DM: Could not find uploader for file '/mnt/ebs/tmp/tmp.AGx2Lqyxbm/Yamba20160415.zip'
process.log.8.gz:Nov  1 17:56:10 10-aws-syd ANMN_NRS: Could not find uploader for file '/mnt/ebs/incoming/ANMN/NRS/IMOS_ANMN-NRS_KOSTUZ_20160408T080040Z_NRSROT_FV01_NRSROT-1604-WQM-24_END-20161012T031745Z_C-20161019T015742Z.nc'
process.log.8.gz:Nov  1 17:57:45 10-aws-syd ANMN_NRS: Could not find uploader for file '/mnt/ebs/incoming/ANMN/NRS/IMOS_ANMN-NRS_KOSTUZ_20160408T081541Z_NRSROT_FV01_NRSROT-1604-WQM-55_END-20161011T060243Z_C-20161019T015744Z.nc'
```

**Comment by mhidas** [comment]
@pblain @smancini Maybe this could be investigated in the next iteration?

**Comment by pblain** [comment]
@mhidas - I'll add a backlog item referencing this so we don't forget it

**Comment by mhidas** [comment]
Now it seems to be permanently broken. I can't see a single case in the logs for the past two weeks where it was able to find the uploader for a file.

**Comment by lwgordonimos** [comment]
It looks to relate to the /etc/incoming-aliases file, as implemented here: https://github.com/aodn/chef/pull/138 

Will need to test whether:

1. the uploaders are in the file or not
2. the file is being managed by Chef as expected
3. if the file is ok, what else the problem could be

**Comment by mhidas** [comment]
The uploaders of the recent files that had this issue are definitely in the /etc/incoming-aliases file on 10-aws-syd.

**Comment by bhasin85** [comment]
![process logs](https://cloud.githubusercontent.com/assets/2552378/21083462/420a88ec-c045-11e6-9a2b-1ea4af5f2cec.png)
![process logs 2](https://cloud.githubusercontent.com/assets/2552378/21083464/44e744e2-c045-11e6-9636-1b72f1387eaf.png)

**Comment by mhidas** [comment]
That was just me (on Dec 8) manually pushing files into incoming, so not surprising it couldn't find an uploader.

**Comment by pmbohm** [comment]
@mhidas Is this still an issue?

**Comment by mhidas** [comment]
Nope, and it will become completely irrelevant with the new pipelines.
