### ISSUE TITLE
ANMN burst average input flag question

### ISSUE THREAD

**Issue by ggalibert** [aodn/data-services#499]
Does [this](https://github.com/aodn/data-services/blob/7e21d8791d5494ff3473f605c717ced749197ef9/ANMN/burst_averaged_product/burst_average.py#L31) come from Monique's original code? Can you explain the rational behind? I'm not sure to understand... I would have removed anything that is not flagged 0, 1 or 2.

**Comment by lbesnard** [comment]
see the 4 lines above Monique's code https://github.com/aodn/data-services/blob/f90a2b417fbdc0218de9b07adcf7bb8b1a0d9581/ANMN/burst_averaged_product/burstproduct/singleWQMburstavproduct.m#L117

**Comment by ggalibert** [comment]
Ok, I can see she removes only flags 4 for 'TURB','FLU2','CPHL','CHLR','CHLU','CHLF' and removes flags 3 and 4 for the rest. I reckon this was based on the fact that the rate of change test which would provide flag 3 is not relevant for bio-optical sensors. Anyway, once again we shouldn't try to interfer with the original content of the FV01 file and assume the QC has been properly performed. Conclusion:  we should remove anything that has a flag >= 3 before averaging.
