### ISSUE TITLE
ANMN burst average clean_burst_vars question

### ISSUE THREAD

**Issue by ggalibert** [aodn/data-services#500]
What is the purpose of this [function](https://github.com/aodn/data-services/blob/7e21d8791d5494ff3473f605c717ced749197ef9/ANMN/burst_averaged_product/burst_average.py#L71)? Would be good to comment better on this.

**Comment by lbesnard** [comment]
basically to get rid of timestamps at the start and end of a FV02 file when all FV02 variables have a NaN value

**Comment by ggalibert** [comment]
Can we rename this function with something like `trim_timestamps_burst_vars` and add your comment above to the code? I didn't find it clear as it is commented now.
