### ISSUE TITLE
IMOS-1.3 checker needs to accept new data centre details

### ISSUE THREAD

**Issue by mhidas** [aodn/data-services#524]
data_centre: eMII => AODN
data_centre_email: info@emii.org.au => info@aodn.org.au

**Comment by mhidas** [comment]
@ggalibert @smancini Do you think the IMOS-1.3 checker should still accept the old values of these details?
For IMOS-1.4 I think we should only accept the new one (even though the document still has the old details)

**Comment by ggalibert** [comment]
It would make sense to me accept both values in at least one of the checker version. It would be a bit harsh to reject eMII in block while this change is still quite recent no?

1.3 -> accepts both.
1.4 -> could accept only AODN. Although it's a bit cheeky since 1.4 doesn't stipulate it.

**Comment by smancini** [comment]
1.3 -> accepts both
1.4 -> only accept AODN. We will help providers to modify files if it fails the test.
