### ISSUE TITLE
burst-averaging code writes creation date in local timezone

### ISSUE THREAD

**Issue by mhidas** [aodn/data-services#557]
The last field in the IMOS filename, and the `date_created` attribute are both supposed to contain the **UTC** date and time the file was created. [burst_average.py](https://github.com/aodn/data-services/blob/master/ANMN/burst_averaged_product/burst_average.py) writes these with the required 'Z' on the end, but the time used is actually local time on wherever the process is running (see lines 218 and 253).

See e.g. https://github.com/aodn/data-services/blob/master/lib/python/IMOSnetCDF.py#L102 for a fix, or why not just use that code, which already generates correct IMOS file names and attributes?

**Comment by mhidas** [comment]
@lbesnard

**Comment by ggalibert** [comment]
I think we can close this, can we?
