### ISSUE TITLE
A couple of issues with python modules used by AIMS realtime scripts

### ISSUE THREAD

**Issue by mhidas** [aodn/data-services#580]
While looking at #578 I noticed that the function `pass_netcdf_checker` seems to be imported from [aims.realtime_util](https://github.com/aodn/data-services/blob/4b0af964d6e2038e447cd3daa9eea450329ff6a2/lib/aims/realtime_util.py) (in [anmn_nrs_aims.py](https://github.com/aodn/data-services/blob/4b0af964d6e2038e447cd3daa9eea450329ff6a2/ANMN/NRS_AIMS/REALTIME/anmn_nrs_aims.py#L42), [faimms.py](https://github.com/aodn/data-services/blob/4b0af964d6e2038e447cd3daa9eea450329ff6a2/FAIMMS/REALTIME/faimms.py#L43), and [soop_trv.py](https://github.com/aodn/data-services/blob/4b0af964d6e2038e447cd3daa9eea450329ff6a2/SOOP/SOOP_TRV/soop_trv.py#L23)) but that module in turn imports it from [util](https://github.com/aodn/data-services/blob/4b0af964d6e2038e447cd3daa9eea450329ff6a2/lib/python/util.py).

Three minor issues with this:
- Why isn't **lib/aims/realtime_util.py** under **lib/python/** ?
- It's generally a good idea to avoid `from module import *`
- Why don't those scripts just import the `pass_netcdf_checker` directly from lib/python/util.py ?

**Comment by lbesnard** [comment]
this resolves the last 2 points
https://github.com/aodn/data-services/pull/622/files
