### ISSUE TITLE
PO BOX - NCCHECKER - issues with tests

### ISSUE THREAD

**Issue by lbesnard** [aodn/data-services#587]
On a brand new po box, after following the instructions on https://github.com/aodn/data-services/blob/master/lib/cc_plugin_imos/README.md

if I run
```bash
cd data-services/lib/cc_plugin_imos
python setup.py test -s cc_plugin_imos.tests
```

I get errors with ncgen

```
writing manifest file 'cc_plugin_imos.egg-info/SOURCES.txt'
running build_ext
ncgen: Protocol error
        (genbin.c:163)
ncgen: Protocol error
        (genbin.c:163)
```

@lwgordonimos @mhidas  any ideas ?

**Comment by lbesnard** [comment]
FI, doing the same thing on AWS10 with a virtual env works.

**Comment by mhidas** [comment]
Humph... probably another netCDF library version issue?

**Comment by mhidas** [comment]
The unittests use `ncgen` to convert the test files from human-readable CDL to binary NetCDF files, but the files you end up with does depend somewhat on the version of the netcdf library you have.

**Comment by lwgordonimos** [comment]
This should not have changed, and in any case, should not be different between PO box and 10.
```bash
lwgordon@10-aws-syd:~$ dpkg -l nco
ii  nco                                                   4.3.4-1                                               command-line operators to analyze netCDF files
lwgordon@10-aws-syd:~$ dpkg -l libnetcdf6
ii  libnetcdf6                                            1:4.1.1-6                                             An interface for scientific data access to large binary data
```

Building PO box now to replicate...
