### ISSUE TITLE
IMOS Checker: wave height variables are not vertical coordinates

### ISSUE THREAD

**Issue by mhidas** [aodn/data-services#593]
The IMOS checker is failing on files containing wave height parameters, which it is erroneously identifying as vertical coordinates. E.g.
```
        float WWSH(TIME) ;
                WWSH:standard_name = "sea_surface_wind_wave_significant_height" ;
                WWSH:long_name = "sea_surface_wind_wave_significant_height" ;
                WWSH:units = "m" ;
                WWSH:reference_datum = "sea surface" ;
                WWSH:positive = "up" ;
```
results in
```
    WWSH                               :3:    20/21 :  
        standard_name                  :3:     1/ 2 :  
            vertical                   :3:     0/ 1 : Variable WWSH appears to
                                                      be a vertical coordinate,
                                                      should have attribute
                                                      standard_name = 'height'
```

**Comment by mhidas** [comment]
@ggalibert I can specifically exclude wave parameters based on `standard_name`, but part the problem is that these variables should not have attributes `reference_datum` or `positive`. I logged this at https://github.com/aodn/imos-toolbox/issues/388

**Comment by ggalibert** [comment]
Fixed in the toolbox by e60b8ac in https://github.com/aodn/imos-toolbox/releases/tag/v2.5.20

**Comment by mhidas** [comment]
This issue has come up again, in a file with variable names like `SIG_WAVE_HEIGHT`. We do need to explicitly exclude any variable that has to do with waves.

**Comment by ggalibert** [comment]
Not sure where that file comes from, ```SIG_WAVE_HEIGHT``` is not used by the toolbox.

**Comment by mhidas** [comment]
@ggalibert It's an ABOS/SOTS file from Pete J.
