### ISSUE TITLE
imos 1.4 checker - acknowledgment attribute issue

### ISSUE THREAD

**Issue by lbesnard** [aodn/data-services#602]
Seems like there are differences between the code defining the acknowledgement attribute
https://github.com/aodn/data-services/blob/master/lib/cc_plugin_imos/cc_plugin_imos/imos.py#L1117

and the 1.4 version of the document
http://content.aodn.org.au/Documents/IMOS/Conventions/IMOS_NetCDF_Conventions.pdf p55

what is the correct version ?

@ggalibert @mhidas

**Comment by bpasquer** [comment]
@lbesnard i think it's fine. I thought i had a similar issue a few weeks ago, but was just cause of an extra space.

**Comment by ggalibert** [comment]
Marty's implementation is correct. Unfortunately there are a few variations out there and the checker allows for that range of variations. The value of the attribute in the convention document complies with the current checker implementation.

**Comment by lbesnard** [comment]
thanks @ggalibert . I've tried with what is in the document. Here is a test file. However it fails passing imos 1.4 . Could you please have a look ?
[IMOS_SRS-OC-BODBAW_X_20040815T005612Z_FK04-FK2_2-absorption-total-AC9_FV02_END-20040815T022313Z_C-20161128T161021Z.nc.zip](https://github.com/aodn/data-services/files/615429/IMOS_SRS-OC-BODBAW_X_20040815T005612Z_FK04-FK2_2-absorption-total-AC9_FV02_END-20040815T022313Z_C-20161128T161021Z.nc.zip)

**Comment by ggalibert** [comment]
> "[...] Data was sourced from the Integrated Marine Observing System (IMOS) -IMOS is supported [...]"

You're missing a space between "-" and "IMOS".

**Comment by lbesnard** [comment]
! thanks a lot

**Comment by mhidas** [comment]
A recurring issue with this (and some other text attributes) is copy-pasting from the conventions document, with all its formatting, into a plain-text netCDF attribute. This can introduce all sort of small differences. They don't really affect the meaning of the attribute, but for the sake of simplicity and sanity, I don't think we should try to allow for these in the checker.

Instead, this would be one good reason for us to produce standard file templates (like the NODC ones) with all these attributes filled in, to make them public, and maybe provide some code/examples to create IMOS data files based on these. The Matlab Toolbox kind of does that already. The [IMOSnetCDF.py](https://github.com/aodn/data-services/blob/master/lib/python/IMOSnetCDF.py) module could be adapted to do this too. See also #525

**Comment by mhidas** [comment]
@lbesnard @ggalibert @bpasquer @smancini Could be worth discussing at some point.
