### ISSUE TITLE
Link Checker unable to send emails

### ISSUE THREAD

**Issue by bhasin85** [aodn/data-services#608]
Update link checker to use AWS SES credentials

**Comment by pblain** [comment]
@atkinsn - Do you know anything about this?  We don't know if it's an issue or not

**Comment by atkinsn** [comment]
I think this referred to the old link checker that was used. I think @kereid or @jachope might know?

**Comment by kereid** [comment]
@atkinsn no we didn't know. @lbesnard does this look familiar to you? Wondering if it's regarding this https://github.com/aodn/data-services/pull/508

**Comment by lbesnard** [comment]
oh I'm getting old (??),  in short nope I can't remember much. It seems like everyone assigned someone else. Maybe @kereid should be assigned ?

**Comment by pblain** [comment]
Since nobody knows what it is I'll close it.
