### ISSUE TITLE
burst-averaging product tweaks

### ISSUE THREAD

**Issue by mhidas** [aodn/data-services#713]
In addition to https://github.com/aodn/data-services/issues/557 and https://github.com/aodn/content/issues/284, a few minor issues I've noticed with the burst-averaged product files:

#### Global attribute `input_file` includes the temporary file name:
e.g. "IMOS/ANMN/.../IMOS_ANMN-QLD_..._C-20170407T041128Z.nc.**PUS3hO**"

#### Standard deviation variables
Should either use the [standard_name modifier](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#standard-name-modifiers) "standard_error" or not have a standard_name attribute.
e.g. `TEMP_burst_sd:standard_name = "sea_water_temperature standard_error" ;`
Standard deviation in temperature is not the same as temperature.

#### Global attribute `comment` repeats comment from input file twice
e.g. Compare global comment in [this file](http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/QLD/GBRHIS/Biogeochem_timeseries/burst-averaged/IMOS_ANMN-QLD_KOSTUZ_20100903T195932Z_GBRHIS_FV02_GBRHIS-1008-WQM-13-burst-averaged_END-20110305T225932Z_C-20170421T081713Z.nc.html) with its [input file](http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/QLD/GBRHIS/Biogeochem_timeseries/IMOS_ANMN-QLD_KOSTUZ_20100903T045914Z_GBRHIS_FV01_GBRHIS-1008-WQM-13_END-20110307T200002Z_C-20170315T015119Z.nc.html).

**Comment by ggalibert** [comment]
> **Standard deviation variables**
> Should either use the [standard_name modifier](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#standard-name-modifiers) "standard_error" or not have a standard_name attribute.

Looks like [standard error and standard deviation are not exactly the same](https://en.wikipedia.org/wiki/Standard_error#Standard_error_of_mean_versus_standard_deviation) so not sure we can use a standard_name modifier for standard deviation variables at this stage.

**Comment by mhidas** [comment]
@ggalibert Thanks. You're right, it's not the same thing. :unamused:

In that case I think those variables should not have a `standard_name` attribute at all.

**Comment by ggalibert** [comment]
There is a lot of parameters that involve 'mean', 'min', 'max' (like IMOS parameter codes WSPD_AVG, WSPD_MIN, WSPD_MAX), etc...

For them as well as for 'mean' and 'standard_deviation', it looks like the [CF cell methods](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#cell-methods) concept (see also [appendix](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#appendix-cell-methods)) would be the way to go. Maybe worth taking into account for the review of the burst averaqed product format.

**Comment by mhidas** [comment]
The current version of the burst-averaging code does already add `cell_methods` attributes to the relevant variables.

**Comment by ggalibert** [comment]
Can we close this issue?
