### ISSUE TITLE
Argo Pipeline - check pipeline status before running cronjob

### ISSUE THREAD

**Issue by lbesnard** [aodn/data-services#834]
Argo cron job starts every few days to rsync new and old data. It checks that there are no files in the $ERROR_DIR of the pipeline project. However if a pipeline is already running, the cron job script doesn't check this. 
This leads to file being deleted which then break the current pipeline.

-> we need to find a solution so a bash script/python script can check the status of supervisorctl pipeline

@smancini

**Comment by lwgordonimos** [comment]
Closing due to creating as backlog item https://github.com/aodn/backlog/issues/900
