### ISSUE TITLE
compliance checker V4 with IMOS plugin - new attribute '_cc_display_headers'

### ISSUE THREAD

**Issue by lbesnard** [aodn/data-services#836]
Related to 
https://github.com/ioos/compliance-checker/pull/560

While testing the compliance checker v4 with the IMOS plugin, I have found an issue with the following file on aws10,  located at ```/mnt/ebs/wip/checker_testing/SRS_OC_LJCO/IMOS_SRS-OC-LJCO_KOSTUZ_20160630T231115Z_SRC_FV01_WQM-hourly.nc```

python:
```python
netcdf_file_path='IMOS_SRS-OC-LJCO_KOSTUZ_20160630T231115Z_SRC_FV01_WQM-hourly.nc'
test = 'imos:1.3'
from compliance_checker.runner import ComplianceChecker, CheckSuite
CheckSuite.load_all_available_checkers()

ComplianceChecker.run_checker(netcdf_file_path, [test], 2, 'normal', output_filename='/tmp/test_cc4', output_format='json')
```

returns
```
    aggregates['scoreheader'] = self.checkers[check_name]._cc_display_headers
AttributeError: type object 'IMOS1_3Check' has no attribute '_cc_display_headers'
```

**Comment by mhidas** [comment]
This is a new attribute of checker classes introduced in v4, which the IMOS checkers don't have yet. I will update. We'll also need to review the way check results are named, as this affects how they are reported in the text output, which has also changed.

**Comment by mhidas** [comment]
Fixed in https://github.com/aodn/cc-plugin-imos/pull/10
